// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "loan-risk/models"

	mock "github.com/stretchr/testify/mock"
)

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: id
func (_m *MockStorer) Get(id int) (*models.LoanApplication, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.LoanApplication
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (*models.LoanApplication, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.LoanApplication); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockStorer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id int
func (_e *MockStorer_Expecter) Get(id interface{}) *MockStorer_Get_Call {
	return &MockStorer_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockStorer_Get_Call) Run(run func(id int)) *MockStorer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockStorer_Get_Call) Return(_a0 *models.LoanApplication, _a1 bool) *MockStorer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_Get_Call) RunAndReturn(run func(int) (*models.LoanApplication, bool)) *MockStorer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: status
func (_m *MockStorer) List(status string) []*models.LoanApplication {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.LoanApplication
	if rf, ok := ret.Get(0).(func(string) []*models.LoanApplication); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanApplication)
		}
	}

	return r0
}

// MockStorer_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockStorer_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - status string
func (_e *MockStorer_Expecter) List(status interface{}) *MockStorer_List_Call {
	return &MockStorer_List_Call{Call: _e.mock.On("List", status)}
}

func (_c *MockStorer_List_Call) Run(run func(status string)) *MockStorer_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorer_List_Call) Return(_a0 []*models.LoanApplication) *MockStorer_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_List_Call) RunAndReturn(run func(string) []*models.LoanApplication) *MockStorer_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: app
func (_m *MockStorer) Save(app *models.LoanApplication) {
	_m.Called(app)
}

// MockStorer_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStorer_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - app *models.LoanApplication
func (_e *MockStorer_Expecter) Save(app interface{}) *MockStorer_Save_Call {
	return &MockStorer_Save_Call{Call: _e.mock.On("Save", app)}
}

func (_c *MockStorer_Save_Call) Run(run func(app *models.LoanApplication)) *MockStorer_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.LoanApplication))
	})
	return _c
}

func (_c *MockStorer_Save_Call) Return() *MockStorer_Save_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorer_Save_Call) RunAndReturn(run func(*models.LoanApplication)) *MockStorer_Save_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockStorer) Stats() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockStorer_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockStorer_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockStorer_Expecter) Stats() *MockStorer_Stats_Call {
	return &MockStorer_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockStorer_Stats_Call) Run(run func()) *MockStorer_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorer_Stats_Call) Return(_a0 map[string]interface{}) *MockStorer_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorer_Stats_Call) RunAndReturn(run func() map[string]interface{}) *MockStorer_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: app
func (_m *MockStorer) Update(app *models.LoanApplication) {
	_m.Called(app)
}

// MockStorer_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStorer_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - app *models.LoanApplication
func (_e *MockStorer_Expecter) Update(app interface{}) *MockStorer_Update_Call {
	return &MockStorer_Update_Call{Call: _e.mock.On("Update", app)}
}

func (_c *MockStorer_Update_Call) Run(run func(app *models.LoanApplication)) *MockStorer_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.LoanApplication))
	})
	return _c
}

func (_c *MockStorer_Update_Call) Return() *MockStorer_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorer_Update_Call) RunAndReturn(run func(*models.LoanApplication)) *MockStorer_Update_Call {
	_c.Run(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, status, notes
func (_m *MockStorer) UpdateStatus(id int, status models.ApplicationStatus, notes string) (*models.LoanApplication, bool) {
	ret := _m.Called(id, status, notes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *models.LoanApplication
	var r1 bool
	if rf, ok := ret.Get(0).(func(int, models.ApplicationStatus, string) (*models.LoanApplication, bool)); ok {
		return rf(id, status, notes)
	}
	if rf, ok := ret.Get(0).(func(int, models.ApplicationStatus, string) *models.LoanApplication); ok {
		r0 = rf(id, status, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(int, models.ApplicationStatus, string) bool); ok {
		r1 = rf(id, status, notes)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockStorer_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStorer_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id int
//   - status models.ApplicationStatus
//   - notes string
func (_e *MockStorer_Expecter) UpdateStatus(id interface{}, status interface{}, notes interface{}) *MockStorer_UpdateStatus_Call {
	return &MockStorer_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status, notes)}
}

func (_c *MockStorer_UpdateStatus_Call) Run(run func(id int, status models.ApplicationStatus, notes string)) *MockStorer_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(models.ApplicationStatus), args[2].(string))
	})
	return _c
}

func (_c *MockStorer_UpdateStatus_Call) Return(_a0 *models.LoanApplication, _a1 bool) *MockStorer_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorer_UpdateStatus_Call) RunAndReturn(run func(int, models.ApplicationStatus, string) (*models.LoanApplication, bool)) *MockStorer_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
