// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "loan-risk/models"

	mock "github.com/stretchr/testify/mock"
)

// MockLoanServicer is an autogenerated mock type for the LoanServicer type
type MockLoanServicer struct {
	mock.Mock
}

type MockLoanServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoanServicer) EXPECT() *MockLoanServicer_Expecter {
	return &MockLoanServicer_Expecter{mock: &_m.Mock}
}

// CalculateEMI provides a mock function with given fields: principal, annualRate, tenureMonths
func (_m *MockLoanServicer) CalculateEMI(principal float64, annualRate float64, tenureMonths int) (*models.EMIResponse, error) {
	ret := _m.Called(principal, annualRate, tenureMonths)

	if len(ret) == 0 {
		panic("no return value specified for CalculateEMI")
	}

	var r0 *models.EMIResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(float64, float64, int) (*models.EMIResponse, error)); ok {
		return rf(principal, annualRate, tenureMonths)
	}
	if rf, ok := ret.Get(0).(func(float64, float64, int) *models.EMIResponse); ok {
		r0 = rf(principal, annualRate, tenureMonths)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EMIResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(float64, float64, int) error); ok {
		r1 = rf(principal, annualRate, tenureMonths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoanServicer_CalculateEMI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateEMI'
type MockLoanServicer_CalculateEMI_Call struct {
	*mock.Call
}

// CalculateEMI is a helper method to define mock.On call
//   - principal float64
//   - annualRate float64
//   - tenureMonths int
func (_e *MockLoanServicer_Expecter) CalculateEMI(principal interface{}, annualRate interface{}, tenureMonths interface{}) *MockLoanServicer_CalculateEMI_Call {
	return &MockLoanServicer_CalculateEMI_Call{Call: _e.mock.On("CalculateEMI", principal, annualRate, tenureMonths)}
}

func (_c *MockLoanServicer_CalculateEMI_Call) Run(run func(principal float64, annualRate float64, tenureMonths int)) *MockLoanServicer_CalculateEMI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(float64), args[1].(float64), args[2].(int))
	})
	return _c
}

func (_c *MockLoanServicer_CalculateEMI_Call) Return(_a0 *models.EMIResponse, _a1 error) *MockLoanServicer_CalculateEMI_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoanServicer_CalculateEMI_Call) RunAndReturn(run func(float64, float64, int) (*models.EMIResponse, error)) *MockLoanServicer_CalculateEMI_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplication provides a mock function with given fields: id
func (_m *MockLoanServicer) GetApplication(id int) (*models.LoanApplication, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 *models.LoanApplication
	var r1 bool
	if rf, ok := ret.Get(0).(func(int) (*models.LoanApplication, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.LoanApplication); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(int) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockLoanServicer_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockLoanServicer_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - id int
func (_e *MockLoanServicer_Expecter) GetApplication(id interface{}) *MockLoanServicer_GetApplication_Call {
	return &MockLoanServicer_GetApplication_Call{Call: _e.mock.On("GetApplication", id)}
}

func (_c *MockLoanServicer_GetApplication_Call) Run(run func(id int)) *MockLoanServicer_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockLoanServicer_GetApplication_Call) Return(_a0 *models.LoanApplication, _a1 bool) *MockLoanServicer_GetApplication_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoanServicer_GetApplication_Call) RunAndReturn(run func(int) (*models.LoanApplication, bool)) *MockLoanServicer_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplications provides a mock function with given fields: status
func (_m *MockLoanServicer) ListApplications(status string) []*models.LoanApplication {
	ret := _m.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for ListApplications")
	}

	var r0 []*models.LoanApplication
	if rf, ok := ret.Get(0).(func(string) []*models.LoanApplication); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LoanApplication)
		}
	}

	return r0
}

// MockLoanServicer_ListApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplications'
type MockLoanServicer_ListApplications_Call struct {
	*mock.Call
}

// ListApplications is a helper method to define mock.On call
//   - status string
func (_e *MockLoanServicer_Expecter) ListApplications(status interface{}) *MockLoanServicer_ListApplications_Call {
	return &MockLoanServicer_ListApplications_Call{Call: _e.mock.On("ListApplications", status)}
}

func (_c *MockLoanServicer_ListApplications_Call) Run(run func(status string)) *MockLoanServicer_ListApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockLoanServicer_ListApplications_Call) Return(_a0 []*models.LoanApplication) *MockLoanServicer_ListApplications_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoanServicer_ListApplications_Call) RunAndReturn(run func(string) []*models.LoanApplication) *MockLoanServicer_ListApplications_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockLoanServicer) Stats() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockLoanServicer_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockLoanServicer_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockLoanServicer_Expecter) Stats() *MockLoanServicer_Stats_Call {
	return &MockLoanServicer_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockLoanServicer_Stats_Call) Run(run func()) *MockLoanServicer_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoanServicer_Stats_Call) Return(_a0 map[string]interface{}) *MockLoanServicer_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoanServicer_Stats_Call) RunAndReturn(run func() map[string]interface{}) *MockLoanServicer_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitApplication provides a mock function with given fields: req, submittedBy
func (_m *MockLoanServicer) SubmitApplication(req models.SubmitApplicationRequest, submittedBy string) (*models.LoanApplication, *models.PipelineSummary, error) {
	ret := _m.Called(req, submittedBy)

	if len(ret) == 0 {
		panic("no return value specified for SubmitApplication")
	}

	var r0 *models.LoanApplication
	var r1 *models.PipelineSummary
	var r2 error
	if rf, ok := ret.Get(0).(func(models.SubmitApplicationRequest, string) (*models.LoanApplication, *models.PipelineSummary, error)); ok {
		return rf(req, submittedBy)
	}
	if rf, ok := ret.Get(0).(func(models.SubmitApplicationRequest, string) *models.LoanApplication); ok {
		r0 = rf(req, submittedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(models.SubmitApplicationRequest, string) *models.PipelineSummary); ok {
		r1 = rf(req, submittedBy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.PipelineSummary)
		}
	}

	if rf, ok := ret.Get(2).(func(models.SubmitApplicationRequest, string) error); ok {
		r2 = rf(req, submittedBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLoanServicer_SubmitApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitApplication'
type MockLoanServicer_SubmitApplication_Call struct {
	*mock.Call
}

// SubmitApplication is a helper method to define mock.On call
//   - req models.SubmitApplicationRequest
//   - submittedBy string
func (_e *MockLoanServicer_Expecter) SubmitApplication(req interface{}, submittedBy interface{}) *MockLoanServicer_SubmitApplication_Call {
	return &MockLoanServicer_SubmitApplication_Call{Call: _e.mock.On("SubmitApplication", req, submittedBy)}
}

func (_c *MockLoanServicer_SubmitApplication_Call) Run(run func(req models.SubmitApplicationRequest, submittedBy string)) *MockLoanServicer_SubmitApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.SubmitApplicationRequest), args[1].(string))
	})
	return _c
}

func (_c *MockLoanServicer_SubmitApplication_Call) Return(_a0 *models.LoanApplication, _a1 *models.PipelineSummary, _a2 error) *MockLoanServicer_SubmitApplication_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLoanServicer_SubmitApplication_Call) RunAndReturn(run func(models.SubmitApplicationRequest, string) (*models.LoanApplication, *models.PipelineSummary, error)) *MockLoanServicer_SubmitApplication_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: id, status, notes
func (_m *MockLoanServicer) UpdateStatus(id int, status models.ApplicationStatus, notes string) (*models.LoanApplication, bool) {
	ret := _m.Called(id, status, notes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *models.LoanApplication
	var r1 bool
	if rf, ok := ret.Get(0).(func(int, models.ApplicationStatus, string) (*models.LoanApplication, bool)); ok {
		return rf(id, status, notes)
	}
	if rf, ok := ret.Get(0).(func(int, models.ApplicationStatus, string) *models.LoanApplication); ok {
		r0 = rf(id, status, notes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoanApplication)
		}
	}

	if rf, ok := ret.Get(1).(func(int, models.ApplicationStatus, string) bool); ok {
		r1 = rf(id, status, notes)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockLoanServicer_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockLoanServicer_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - id int
//   - status models.ApplicationStatus
//   - notes string
func (_e *MockLoanServicer_Expecter) UpdateStatus(id interface{}, status interface{}, notes interface{}) *MockLoanServicer_UpdateStatus_Call {
	return &MockLoanServicer_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", id, status, notes)}
}

func (_c *MockLoanServicer_UpdateStatus_Call) Run(run func(id int, status models.ApplicationStatus, notes string)) *MockLoanServicer_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(models.ApplicationStatus), args[2].(string))
	})
	return _c
}

func (_c *MockLoanServicer_UpdateStatus_Call) Return(_a0 *models.LoanApplication, _a1 bool) *MockLoanServicer_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoanServicer_UpdateStatus_Call) RunAndReturn(run func(int, models.ApplicationStatus, string) (*models.LoanApplication, bool)) *MockLoanServicer_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoanServicer creates a new instance of MockLoanServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoanServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoanServicer {
	mock := &MockLoanServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
